name: Test

on:
  workflow_dispatch:
    inputs:
      header_color:
        description: Header color
        required: true
        type: string
      header_title:
        description: Header title
        required: true
        type: string

jobs:
  test-notify:
    runs-on: ubuntu-latest
    name: Test Notify
    steps:
      - name: Notify
        uses: northwang-lucky/chatbot-webhook-client@v1.1.1
        with:
          app: Lark
          webhook: ${{ secrets.CUSTOM_BOT_WEBHOOK }}
          secret: ${{ secrets.CUSTOM_BOT_SECRET }}
          template: file://.template/message.json
          params: >-
            {
              "repository": "${{ github.repository }}",
              "ref_name": "${{ github.ref_name }}",
              "event_name": "${{ github.event_name }}",
              "short_sha": "${{ github.workflow }}",
              "commit_message": "${{ github.event.head_commit.message }}",
              "actor": "${{ github.actor }}",
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
